# Site settings
title:       Ulf Schneider – Developer and Agile Coach 
description: Hi, I´m Ulf Schneider, a developer and agile coach living in Paderborn, Germany.
author:      Ulf Schneider
url:         https://ulf.codes # the base hostname & protocol for the site
excerpt_separator: "<!-- more -->"
markdown:    kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true
include:     ["_pages"]

rss:          /feed.rss
colophon:     /colophon/
ownership:    /ownership/

defaults:
  - 
    scope:
      path: "" 
    values:
      layout: default
  - 
    scope:     
      path: _pages 
      type: pages
    values:
      permalink: /:title/
  - 
    scope:      
      path: _posts
      type: posts
    values:
      permalink: /:categories/:title/



