# Site settings
title:       Hi, I am Ulf Schneider 
description: Hi, I am Ulf Schneider, a developer and agile coach living in Paderborn, Germany.
author:      Ulf Schneider
url:         https://ulf.codes # the base hostname & protocol for the site

markdown:    kramdown
include:     ["_pages"]

rss:          /feed.xml
colophon:     /colophon

defaults:
  - 
    scope:
      path: "" 
    values:
      layout: default
  - 
    scope:     
      path: _pages 
      type: pages
    values:
      permalink: /:title/
  - 
    scope:      
      path: _posts
      type: posts
    values:
      permalink: /:categories/:title/


plugins:
  - jekyll-feed


