# Site settings
title:       Hi, I´m Ulf Schneider 
description: Hi, I´m Ulf Schneider, a developer and agile coach living in Paderborn, Germany.
author:      Ulf Schneider
url:         https://ulf.codes # the base hostname & protocol for the site
excerpt_separator: "<!-- more -->"
markdown:    kramdown
include:     ["_pages"]

rss:          /feed.rss
colophon:     /colophon/

defaults:
  - 
    scope:
      path: "" 
    values:
      layout: default
  - 
    scope:     
      path: _pages 
      type: pages
    values:
      permalink: /:title/
  - 
    scope:      
      path: _posts
      type: posts
    values:
      permalink: /:categories/:title/



