# Site settings
title:       Ulf Schneider #title of the page
meta:        Ulf Schneider Agile Paderborn
# baseurl:   the subpath of the site, e.g. /blog/
name:        Ulf Schneider
url:         https://ulf.codes # the base hostname & protocol for the site

# Build settings
markdown:    kramdown
include:     ['_pages']
permalink:   '/:title/'
plugins:
  - jekyll-feed
