# Site settings
title:       Ulf Schneider 
description: Hi, I am Ulf Schneider. I am a developer and agile coach living in Paderborn, Germany.
author:      Ulf Schneider
url:         https://ulf.codes # the base hostname & protocol for the site

markdown:    kramdown
include:     ['_pages']
permalink:   '/:title/'

plugins:
  - jekyll-feed


