# Site settings
title: Ulf Schneider
description: Developer • Agile Coach
meta: Ulf Schneider Agile Paderborn
baseurl:  # the subpath of your site, e.g. /blog/
name: Ulf Schneider
url: http://ulf.codes # the base hostname & protocol for thesite

# Build settings
markdown: kramdown
include: ['_pages']
permalink: '/:title/'
