# Site settings
title: Ulf Schneider #title of the page
description: Agile Worker
meta: Ulf Schneider Agile Paderborn
baseurl:  # the subpath of the site, e.g. /blog/
name: Ulf Schneider
url: http://ulf.codes # the base hostname & protocol for thesite
twitter_prompt: Follow me via #something like: Follow me via
twitter_username: ulfeed #twitter user

# Build settings
markdown: kramdown
include: ['_pages']
permalink: '/:title/'
